version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
    ports:
      - "${POSTGRES_PORT}:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

#  web:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    command: poetry run python manage.py runserver 0.0.0.0:8000
#    volumes:
#      - ./backend:/app
#    ports:
#      - "8000:8000"
#    environment:
#      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
#      - DJANGO_DEBUG=${DJANGO_DEBUG}
#      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
#      - POSTGRES_DB=${POSTGRES_DB}
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#      - POSTGRES_HOST=db
#      - POSTGRES_PORT=5432
#      - REDIS_URL=redis://redis:6379/0
#    depends_on:
#      - db
#      - redis

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A backend worker --loglevel=info --pool=solo
    volumes:
      - ./backend:/app
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=5432
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
